/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __KALDI_MARSHAL_MARSHAL_H__
#define __KALDI_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:STRING (/home/fhq/gst-plugin/kaldimarshal.list:1) */
#define kaldi_marshal_VOID__STRING	g_cclosure_marshal_VOID__STRING


G_END_DECLS

#endif /* __KALDI_MARSHAL_MARSHAL_H__ */
